name: xprec python package

on:
  push:
    branches:
      mainline
  pull_request:
    branches:
      mainline

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            numpy-version: 1.16
            python-version: 3.6
          - os: ubuntu-latest
            numpy-version: auto
            python-version: 3.9
          - os: ubuntu-latest
            numpy-version: 2.0
            python-version: 3.11
          - os: windows-latest
            numpy-version: auto
            python-version: 3.9
          - os: macos-12
            numpy-version: auto
            python-version: 3.9
          - os: macos-latest
            numpy-version: auto
            python-version: 3.11
    steps:
    steps:
      - uses: actions/checkout@v4

      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install numpy ${{ matrix.numpy-version }}
        if: ${{ matrix.numpy-version != 'auto' }}
        run: |
          pip install numpy==${{ matrix.numpy-version }}

      - name: Install package with testing dependencies
        run: |
          pip install -v .[test]

      - name: Test with pytest
        run: |
          pytest
