name: Build and upload to PyPI

# Triggered a new tag starting with "v" is pushed
on:
  push:
    tags:
      - 'v*'

jobs:
  build_sdist:
    name: Build distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Examine system
        run: pip freeze --all

      - name: Build sdist
        run: python setup.py sdist

      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/xprec-*.tar.gz

  upload_pypi:
    name: Upload to PyPI
    needs: [build_sdist]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist

      - uses: pypa/gh-action-pypi-publish@v1.4.2
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          skip_existing: true
